name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Build Package
        run:
          pip install poetry && poetry build

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1